services:
  app:
    container_name: livestreamer
    build: .
    volumes:
      # - ./dist:/opt/livestreamer
      - appdata:/var/opt/livestreamer
    restart: no
    ports:
      - 8120:8120 # http
      - 8121:8121 # https
      - 9229:9229 # node debug root
      - 9230:9230 # node debug media-server
      - 9231:9231 # node debug file-manager
      - 9232:9232 # node debug main
    networks:
      - livestreamer

networks:
  livestreamer:

volumes:
  appdata: